### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Aslemammad** [hiradary/reoverlay#2]
Hello Hirad✋, If you want, I could convert the JS to TS project and add more features.😍

**Comment by hiradary** [comment]
Hey @Aslemammad! That's awesome. I can't wait to see that.

**Comment by Aslemammad** [comment]
I'll add declaration typescript file

**Comment by hiradary** [comment]
@Aslemammad PRs are Welcome! Thanks

**Comment by Aslemammad** [comment]
I had much problems with generating .d.ts for the project, I may take it another time, So I'll close this issue. Thanks
