### ISSUE TITLE
Security issue in dependency

### ISSUE THREAD

**Issue by ottovw** [hiradary/reoverlay#25]
![image](https://user-images.githubusercontent.com/1045946/152617676-440bbae7-e3e3-4232-a060-10623b9a38b8.png)

**Comment by hiradary** [comment]
@ottovw Thanks for reporting! Will get this fixed in the next couple of days. I'm thinking about doing a complete re-write with Typescript.

**Comment by hiradary** [comment]
@ottovw I've published a new release (v1.0.3). Please try the latest version, it should be good now.
