### ISSUE TITLE
Scrollable Content

### ISSUE THREAD

**Issue by ottovw** [hiradary/reoverlay#9]
Hi, i really love the way you are handling Modals.

I'm struggling to use it though with Big contents, which needs vertical scrolling. 

The goal is to create a 80% width and 80% height modal with scrollable content. Am i doing something wrong or the sizing an actual problem?

**Comment by hiradary** [comment]
Hi @ottovw,

It's great that you like the approach. Regarding your issue, you can actually create your own `ModalContainer` and wrap your component inside of it. It allows you to have scrollable content, custom animations, etc.

Maybe I should a section in docs, explaining this in a real-world example.

**Comment by ottovw** [comment]
It works. Thanks!

Adding documentation would be great!
